CREATE DATABASE sensorial;
CREATE TABLE PROYECTO(
	PROY_CODE INT NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE STATUS_RECORD(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PROY_CODE INT NOT NULL,
    TEMPERATURA DECIMAL(4, 2),
    HUMEDAD DECIMAL(4, 2),
    EXTRACTORES INT,
    NEBULIZADORES INT,
    FOREIGN KEY(PROY_CODE) REFERENCES PROYECTO(PROY_CODE)
);

CREATE TABLE PARAMETROS(
	PROY_CODE INT NOT NULL,
	    TEM_MAX DECIMAL,
	    HUM_MAX DECIMAL,
	    HUM_MIN DECIMAL,
	    FOREIGN  KEY(PROY_CODE) REFERENCES PROYECTO(PROY_CODE)
);
